import DefaultHead from 'components/SEO/DefaultHead';
import { useTranslations } from 'next-intl';

export default function Head() {
  const t = useTranslations('pages.home.SEO');

  return (
    <>
      <DefaultHead />

      {/* <title>Create Next App</title> */}
      <title>{t('title')}</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
