import DefaultHead from '@components/SEO/DefaultHead';

export default function Head() {
  return (
    <>
      <DefaultHead />

      <title>Create Next App</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </>
  );
}
